title:              FutureLab Nepal
email:              futurelab.nepal@gmail.com
description:        Where Learning Happens
author:             FutureLab Nepal
baseurl:            ""
url:                ""

# Social Profiles
twitter_username:   futurelab_nepal
github_username:    futurelab-nepal
facebook_username:  futurelab.nepal
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site


